name: TeleportPlugin
version: 1.0.0
main: me.george.plugin.TeleportPlugin
api-version: 1.19
description: A simple teleportation plugin for Minecraft.
author: George
commands:
  teleportmenu:
    description: Opens the teleport GUI
    usage: /teleportmenu
    permission: teleportplugin.teleport
    aliases: [tpmenu]
  teleportaddworld:
    description: Adds a world to the teleport menu
    usage: /teleportaddworld <worldname>
    permission: teleportplugin.teleportaddworld
    aliases: [tpaw]
  teleportremoveworld:
    description: Removes a world from the teleport menu
    usage: /teleportremoveworld <worldname>
    permission: teleportplugin.teleportremoveworld
    aliases: [tprw]
  teleportlistworlds:
    description: Lists all available worlds for teleportation
    usage: /teleportlistworlds
    permission: teleportplugin.teleportlistworlds
    aliases: [tplw]
permissions:
  teleportplugin.teleport:
    description: Allows a player to use the teleport command.
    default: true
  teleportplugin.teleportaddworld:
    description: Allows an operator to add worlds to the teleport menu.
    default: op
  teleportplugin.teleportremoveworld:
    description: Allows an operator to remove worlds from the teleport menu.
    default: op
  teleportplugin.teleportlistworlds:
    description: Allows a player to list all available worlds for teleportation.
    default: op
